#!/bin/python3

import os
import sys


# Complete the gradingStudents function below.

def gradingStudents(grades):
    myres =  []
    for i in grades:
        if i<38:
            myres.append(i)
        else:
            n = i%5
            a = 5-n
            if a<3:
                myres.append(i+a)
            else:
                myres.append(i)
                
    return myres




if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    grades = []

    for _ in range(n):
        grades_item = int(input())
        grades.append(grades_item)

    result = gradingStudents(grades)

    f.write('\n'.join(map(str, result)))
    f.write('\n')

    f.close()
